// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_dificuldade_1800_insano = "CgkI8LW0358VEAIQAw"; // <GPGSID>
        public const string achievement_dificuldade_3000_cego = "CgkI8LW0358VEAIQBQ"; // <GPGSID>
        public const string achievement_dificuldade_1000_veterano = "CgkI8LW0358VEAIQAg"; // <GPGSID>
        public const string achievement_dificuldade_2400_baixa_viso = "CgkI8LW0358VEAIQBA"; // <GPGSID>
        public const string achievement_dificuldade_5000_criador = "CgkI8LW0358VEAIQBg"; // <GPGSID>
        public const string achievement_dificuldade_500_iniciante = "CgkI8LW0358VEAIQAQ"; // <GPGSID>

}

